server:
  port: 8090
  ssl:
    key-store: ./keystore.p12
    key-store-password: cymophane
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update  # Change from 'create-drop' to 'update'
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: MySQL
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    databaseName: realestate
    url: jdbc:mysql://mysql_realestate:3306/${spring.datasource.databaseName}
    username: root
    password:

application:
  security:
    jwt:
      secret-key: 8d4fed75477d160c393db8a22edce23a5ae7971b4533077d89ac0016dd92c879d21791073310294924cb896443a8214cfdc129baa42af8b3030a397382a93532
      expiration: 86400000 # 24/7
      refresh-token:
        expiration: 604800000 # 7 days
  custom:
    file-storage:
      image-directory: ./resources/images
    maximum-file-size:
      property-images: 10000000
